language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
before_install:
  - python --version
  - pip install -U pip
  - pip install pytest pytest-cov pylint
install:
  - pip install ".[test]" .
script: pytest --cov=./
after_success:
  - bash <(curl -s https://codecov.io/bash)